/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author usuario
 */
public class ejercicio11 extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio11
     */
    public ejercicio11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numero1 = new javax.swing.JTextField();
        numero2 = new javax.swing.JTextField();
        enviar = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("cual es la cantidad de empanadas que desea comprar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 330, 20));

        jLabel2.setText("cada empanada cuesta");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, 30));
        getContentPane().add(numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 60, 30));
        getContentPane().add(numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 60, 30));

        enviar.setText("enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 350, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        // TODO add your handling code here:
        float n1=Integer.parseInt(numero1.getText());
        float n2=Integer.parseInt(numero2.getText());
        float r1;
        float r2;
        float r3;
                
        if(n1>=300){
            r1=(float) ((n2*n1)*0.30);
            r2=n2*n1;
            r3=r2-r1;
            resultado.setText("La cantidad a pagar es de: " + r3);
        }
        else{
            if(n1>200 && n1<300){
                r1=(float) ((n2*n1)*0.20);
                r2=n2*n1;
                r3=r2-r1;
                resultado.setText("La cantidad a pagar es de: " + r3);
            }
            else{
                if(n1>=100 && n1<=200){
                   r1=(float) ((n2*n1)*0.10);
                   r2=n2*n1;
                   r3=r2-r1;
                   resultado.setText("La cantidad a pagar es de: " + r3); 
                }
                else{
                    if(n1>50 && n1<100){
                      r1=(float) ((n2*n1)*0.05);
                      r2=n2*n1;
                      r3=r2-r1;
                   resultado.setText("La cantidad a pagar es de: " + r3);  
                    }
                    else{
                        if(n1>=1 && n1<=50){
                        
                        r2=n2*n1;
                        
                      resultado.setText("No tiene descuento, el total a pagar es de: " + r2);    
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField numero1;
    private javax.swing.JTextField numero2;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
