/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author noskcire
 */
public class ejercicio7 extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio7
     */
    
    public static String clase;
    public static String destino;
    public static String tipo;
    
    public ejercicio7() {
        initComponents();
        //añadiendo campos al jcombo clase
        clases.addItem("Primera Clase");
        clases.addItem("Segunda Clase");
        clases.addItem("Tercera Clase");
        
        //añadiendo campos al jcombo destino
        destinos.addItem("Miami");
        destinos.addItem("Madrid");
        
        //añadiendo campos al jcombo tipo
        tipos.addItem("Negocios");
        tipos.addItem("Familiar");
        tipos.addItem("Turista");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();
        pasajes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextPane();
        destinos = new javax.swing.JComboBox<>();
        tipos = new javax.swing.JComboBox<>();
        clases = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre: ");

        jLabel2.setText("Destino: ");

        jLabel3.setText("Cedula: ");

        jLabel4.setText("Tipo de Viaje: ");

        jLabel5.setText("Clase: ");

        jLabel6.setText("Nro. Pasajes: ");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(resultado);

        destinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinosActionPerformed(evt);
            }
        });

        tipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiposActionPerformed(evt);
            }
        });

        clases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasesActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("VIENTOS AIR");
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clases, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(cedula))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(destinos, 0, 98, Short.MAX_VALUE)
                            .addComponent(tipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pasajes))))
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel7)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(pasajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nom = (nombre.getText());
        int ced = Integer.parseInt(cedula.getText());
        int numpasaje = Integer.parseInt(pasajes.getText());
        double valor, descuento, descuento_parcial, descuento2, valor_total;
        valor = 0;
        descuento = 0;
        
        //Comparamos la clase y el destino para obtener el valor del tikeck
        
        if(clase.equals(("Primera Clase")) && destino.equals("Miami")){
            valor = 1300000;
        }
        if(clase.equals(("Primera Clase")) && destino.equals("Madrid")){
            valor = 2700000;
        }
        if(clase.equals(("Segunda Clase")) && destino.equals("Miami")){
            valor = 1120000;
        }
        if(clase.equals(("Segunda Clase")) && destino.equals("Madrid")){
            valor = 2500000;
        }
        if(clase.equals(("Tercera Clase")) && destino.equals("Miami")){
            valor = 1100000;
        }
        if(clase.equals(("Tercera Clase")) && destino.equals("Madrid")){
            valor = 2320000;
        }
        
        //
        
        if(tipo.equals(("Negocios"))){
            descuento = 0;
        }
        if(tipo.equals(("Familiar"))){
            descuento = (valor * numpasaje) * 0.07;
        }
        if(tipo.equals("Turista")){
            descuento = (valor * numpasaje) * 0.0475;
        }
        
        descuento_parcial = (valor * numpasaje) - descuento;
        
        if((numpasaje >= 3) && (numpasaje <= 6)){
            descuento2 = descuento_parcial * 0.026;
            resultado.setText("Nombre: " + nom + "      " + "Cedula: " + ced + "\n "+ "\nClase: " + clase + "               " + "Destino: " + destino + "\n" + "\nTipo de viaje: " + tipo + "             " + "Total a pagar: " + (descuento_parcial - descuento2));
            }else{
                 if((numpasaje >= 6 ) && (numpasaje <= 10)){
                     descuento2 = descuento_parcial * 0.0538;
                     resultado.setText("Nombre: " + nom + "      " + "Cedula: " + ced + "\n "+ "\nClase: " + clase + "               " + "Destino: " + destino + "\n" + "\nTipo de viaje: " + tipo + "             " + "Total a pagar: " + (descuento_parcial - descuento2));
                 }else{
                     if(numpasaje >= 11){
                         descuento2 = descuento_parcial * 0.0724;
                         resultado.setText("Nombre: " + nom + "      " + "Cedula: " + ced + "\n "+ "\nClase: " + clase + "               " + "Destino: " + destino + "\n" + "\nTipo de viaje: " + tipo + "             " + "Total a pagar: " + (descuento_parcial - descuento2));
                     }else{
                         resultado.setText("Nombre: " + nom + "      " + "Cedula: " + ced + "\n "+ "\nClase: " + clase + "               " + "Destino: " + destino + "\n" + "\nTipo de viaje: " + tipo + "             " + "Total a pagar: " + (descuento_parcial));
                     }
                 }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasesActionPerformed
        // TODO add your handling code here:
        clase= (String)clases.getSelectedItem();
    }//GEN-LAST:event_clasesActionPerformed

    private void destinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinosActionPerformed
        // TODO add your handling code here:
        destino = (String)destinos.getSelectedItem();
    }//GEN-LAST:event_destinosActionPerformed

    private void tiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiposActionPerformed
        // TODO add your handling code here:
        tipo = (String)tipos.getSelectedItem();
    }//GEN-LAST:event_tiposActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejercicio7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedula;
    private javax.swing.JComboBox<String> clases;
    private javax.swing.JComboBox<String> destinos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField pasajes;
    private javax.swing.JTextPane resultado;
    private javax.swing.JComboBox<String> tipos;
    // End of variables declaration//GEN-END:variables
}
